### ISSUE TITLE
Alternative UI to show more info in less space?

### ISSUE THREAD

**Issue by NitrOP7674** [BenTheDan/IngameRank#1]
First off, thank you for this plugin, it's really great to be able to easily see comp ranks for everyone in casual or extra modes!

I am thinking it could be even more useful to be able to see all of a player's comp mode rankings at the same time, using the same three-column format already used.  But instead of showing:

> `<MODE> <RANK> <DIV>`

Show:

> `<1's RANK>  <2's RANK> <3's RANK>`

With the division either omitted or rendered as a small text number on top of the rank symbol (maybe at the bottom right in a small font).  Do you think something like this would be possible?

**Comment by BenTheDan** [comment]
Thank you for taking the time to provide feedback. 
Unfortunately, I no longer intend to work on this plugin, which as I recently found out is [no longer accurate](https://bakkesplugins.com/plugins/view/282).
If you would like to make the changes yourself feel free to fork the repo.
Alternatively you could use the [Tracker Network App](https://rocketleague.tracker.network/rocket-league/app) aswell.

**Comment by NitrOP7674** [comment]
Aw that's a bummer. Maybe I'll fork it and make it show raw MMR numbers instead, if I can find the time. Thanks!
