### ISSUE TITLE
Updated scoreboard

### ISSUE THREAD

**Issue by ghost** [BenTheDan/IngameRank#11]
![Icons](https://github.com/BenTheDan/IngameRank/assets/134888814/cb8a00e8-6ed1-48b4-9056-fa56f1a70302)
After the update and the start of the 14th season, the scoreboard was moved a little lower, and the rank icons remained at the same level. I know that work on the mod is no longer in progress, so I want to ask how it can be fixed. I was looking at the code and trying to find where I could change the position of the icons to a few pixels lower, but I didn't understand anything (spoiler alert, I didn't learn C++) so I'm asking for help. Even if no one sees it and I can't fix it, it's okay, I'll just have to play without the mod. Perfectionism just tears me apart😩

**Comment by BenTheDan** [comment]
Hey,

The issue will be fixed in the next patch (v1.2 pending review)
