### ISSUE TITLE
looks weird

### ISSUE THREAD

**Issue by hhoneeyy** [BenTheDan/IngameRank#12]
![image](https://github.com/BenTheDan/IngameRank/assets/86309103/17fd3df9-0b30-428d-8a94-6f3899397c43)
i liked the old one better, the black one. also the icon is still misaligned

**Comment by BenTheDan** [comment]
Hey,

I you prefer the original textures you can download them from here: [assets.zip](https://github.com/BenTheDan/IngameRank/blob/68f5a63dca92fe85bf673202117cbb25d1fc4f6f/assets.zip)
Unzip the archive, find the folder titled "IngameRank", and drag and drop it to &lt;Bakkesmod Folder>/data/assets

As for the misalignment is the screenshot taken during an instant replay of a goal?
If not can you send these settings:
Screen Resolution e.g.: (1920*1080),
Interface Scale,
Display Scale,
and what gamemode you were playing

**Comment by hhoneeyy** [comment]
> Hey,
> 
> I you prefer the original textures you can download them from here: [assets.zip](https://github.com/BenTheDan/IngameRank/blob/68f5a63dca92fe85bf673202117cbb25d1fc4f6f/assets.zip) Unzip the archive, find the folder titled "IngameRank", and drag and drop it to <Bakkesmod Folder>/data/assets
> 
> As for the misalignment is the screenshot taken during an instant replay of a goal? If not can you send these settings: Screen Resolution e.g.: (1920*1080), Interface Scale, Display Scale, and what gamemode you were playing

![image](https://github.com/BenTheDan/IngameRank/assets/86309103/0cb5ac4e-a013-4f50-9aab-d823c0e6aab0)
i was playing casual 1s, but the misalignment is in all gamemodes. my scaling is set to 125% and here are my settings. the screenshot was taken after the opponent forfeited

**Comment by BenTheDan** [comment]
If the screenshot was taken after forfeit, that means it was during an instant replay, otherwise the match would have ended immediately.
During an instant replay the green check marks would overlap with the rank images when a player hits skip.
The images moving to the left is intended behavior meant to prevent this overlap.

If you are referring to the platform logo not being in the right place, that is a different plugin.

**Comment by hhoneeyy** [comment]
> If the screenshot was taken after forfeit, that means it was during an instant replay, otherwise the match would have ended immediately. During an instant replay the green check marks would overlap with the rank images when a player hits skip. The images moving to the left is intended behavior meant to prevent this overlap.
> 
> If you are referring to the platform logo not being in the right place, that is a different plugin.

i mean the misalignments are always there

**Comment by hhoneeyy** [comment]
i got it, thanks! <3
