### ISSUE TITLE
Plugin doesn't work at all

### ISSUE THREAD

**Issue by FeelsLevi** [BenTheDan/IngameRank#17]
My plugin doesn't work, I've redownloaded it a million times, please help

**Comment by BenTheDan** [comment]
Hey,

Try these steps to make sure the plugin is working as intended:

- Check if the plugin is enabled in the plugin manager
- Check if the plugin is enabled in the plugin settings
- Check if Show mmr on scoreboard and Show mmr in casual playlists are enabled in the bakkesmod ranked menu
- Make sure you're playing online matches as the plugin doesn't work in private and offline games

If it still doesn't work, try reinstalling bakkesmod

**Comment by FeelsLevi** [comment]
Hes, thanks for answering very quickly, the plugin wasn’t enabled, that was
the problem, thanka for helping.

Have a good day!

BenTheDan ***@***.***> (időpont: 2024. nov. 9., Szo, 10:56)
ezt írta:
