### ISSUE TITLE
[Feature request] show current rank instead of highest ever reached

### ISSUE THREAD

**Issue by red9350** [BenTheDan/IngameRank#4]
Would it be possible to show the current rank instead of the highest rank ever reached?

**Comment by BenTheDan** [comment]
Hey,

Thanks for reaching out! The plugin always gets the current MMR values from bakkesmod's GetPlayerMMR function. This means that as long as bakkesmod updates the MMRs the plugin should update accordingly and display the current rank. 
As I remember, something that can cause bakkesmod not to update the MMR is if you leave a match before it ends, eg. during the instant replay of the last goal. This is resolved once you play a match and wait for it to end and the winner be announced.
If you still encounter the issue please contact me with some more details.

**Comment by red9350** [comment]
Thanks for the reply! It was my mistake: it correctly shows the current rank when i change the selected playlist pressing F8. Strangely though it seems to not save my preferences when choosing a playlist from the plugin settings, i.e. if I choose Standard in the dropdown and i close and reopen the plugin settings, it will be back to Best

**Comment by BenTheDan** [comment]
Do you have Auto Playlist enabled? It automatically sets the playlist to the one you're playing when you join a match, which in case of casual is Best.
