### ISSUE TITLE
[Feature request] Current playlist

### ISSUE THREAD

**Issue by ghost** [BenTheDan/IngameRank#8]
I'm not sure if this plugin is still maintained, but I think its worth a shot. I think adding a "current playlist" option would be awesome. It will let you more accurately gauge your opponents skill in that playlist.

**Comment by kevinmlsilva** [comment]
https://github.com/BenTheDan/IngameRank/issues/4#issuecomment-1250387916

**Comment by BenTheDan** [comment]
The auto playlist option is replaced by "current" in the playlist selection in the next patch (v1.2)
